console.log(process.env)
console.log("------------------------")
console.log(process.arch)
console.log("------------------------")
console.log(process.uptime())
console.log("------------------------")
console.log(process.memoryUsage())
console.log("------------------------")
console.log(process.version)
console.log("------------------------")
console.log(process.versions)
console.log("------------------------")

console.log(`Number : ${1} + ${2} = ${3 + 4}`)
console.log(`String : ${"Hello World"}`)
console.log(`JSON : %j`, {name : 'node.js'})
console.log(`String1` ,`String2`)